
server:
  port: 8080

spring:
  application:
    name: example
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      data-locations:
        - classpath:test-data.sql

  graphql:
    graphiql:
      enabled: true

logging:
  level:
    root: INFO

