
server:
  port: 8080

spring:
  application:
    name: example
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

  graphql:
    graphiql:
      enabled: true

logging:
  level:
    root: INFO

